# Generated by Django 5.2.14 on 2026-06-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/profile_pictures/"
            ),
        ),
    ]
