# Generated by Django 5.2.14 on 2026-06-19 16:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to=accounts.models._profile_thumb_path,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models._profile_image_path
            ),
        ),
    ]
