# Generated by Django 5.2.14 on 2026-05-27 15:53

import django.db.models.deletion
import mediafiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=mediafiles.models.post_file_upload_path,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "file_type",
                    models.IntegerField(
                        choices=[
                            (1, "pdf"),
                            (2, "word"),
                            (3, "powerpoint"),
                            (4, "image"),
                            (5, "excel"),
                            (6, "undefined"),
                        ],
                        default=6,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_downloadable", models.BooleanField(default=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="content.post",
                    ),
                ),
            ],
        ),
    ]
