# Generated by Django 5.2.15 on 2026-06-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediafiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postfile",
            name="file_type",
            field=models.IntegerField(
                choices=[
                    (1, "pdf"),
                    (2, "word"),
                    (3, "powerpoint"),
                    (4, "image"),
                    (5, "excel"),
                    (6, "undefined"),
                    (7, "archive"),
                ],
                default=6,
            ),
        ),
    ]
