# Generated by Django 5.2.14 on 2026-05-28 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=60, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, editable=False, max_length=60, unique=True
                    ),
                ),
                ("level", models.PositiveIntegerField(default=1, editable=False)),
                ("path", models.CharField(blank=True, max_length=500, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="content.category",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="images/default_images/blank_post_thumbnail.png",
                        upload_to="images/post_thumbnails/",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("content", models.TextField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "draft"), (2, "published")], default=2
                    ),
                ),
                ("links", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("published_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, editable=False, max_length=255, unique=True
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="accounts.profile",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="content.category"
                    ),
                ),
                (
                    "tag",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="content.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
    ]
