# Generated by Django 5.2.14 on 2026-06-19 20:39

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_post_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                max_length=255,
                null=True,
                upload_to=content.models._post_thumb_path,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="thumbnail_small",
            field=models.ImageField(
                blank=True,
                editable=False,
                max_length=255,
                null=True,
                upload_to=content.models._post_thumb_small_path,
            ),
        ),
    ]
