# Generated by Django 5.2.14 on 2026-05-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_category_slug_alter_post_slug_alter_tag_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.AddField(
            model_name="category",
            name="parents",
            field=models.ManyToManyField(
                blank=True, related_name="children", to="content.category"
            ),
        ),
    ]
