# Generated by Django 5.2.14 on 2026-06-19 21:05

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_post_thumbnail_post_thumbnail_small"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=content.models._post_image_path,
            ),
        ),
    ]
