# Generated by Django 5.2.14 on 2026-05-27 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_remove_category_parent_category_parents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parents",
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="content.category",
            ),
        ),
    ]
