FROM python:3.12-slim
LABEL maintainer="artinbilehjani@gmail.com"

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Apply mirror to all pip installs
ENV PIP_INDEX_URL=https://mirror-pypi.runflare.com/simple

WORKDIR /app

COPY requirements.txt /app/

RUN python -m pip install --upgrade pip && python -m pip install -r requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    gcc \
    libjpeg62-turbo-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

COPY 01_requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./core /app/
COPY core/ /app/

EXPOSE 8000
