# Generated by Django 5.2.14 on 2026-05-27 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("published_date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("features", "Features"),
                            ("about", "About"),
                            ("cta", "Call To Action"),
                            ("contact", "Contact"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_title", models.CharField(blank=True, max_length=250, null=True)),
                ("homepage_hero_text", models.TextField(blank=True, null=True)),
                ("contact_info", models.TextField(blank=True, null=True)),
                ("footer_text", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
