# Generated by Django 5.2.14 on 2026-06-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagesection",
            name="button_label",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="button_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="icon",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="subtitle",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
