# Generated by Django 5.2.14 on 2026-06-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_homepagesection_button_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero"),
                    ("features", "Features"),
                    ("features_title", "Features Title"),
                    ("about", "About"),
                    ("cta", "Call To Action"),
                    ("contact", "Contact"),
                ],
                max_length=50,
            ),
        ),
    ]
